# DreamEcho Xcode 项目配置
# 使用 XcodeGen 自动生成项目文件
# 安装: brew install xcodegen
# 运行: xcodegen generate

name: DreamEcho

options:
  bundleIdPrefix: com.epwujiajun
  deploymentTarget:
    iOS: 16.0
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    PRODUCT_NAME: DreamEcho
    PRODUCT_BUNDLE_IDENTIFIER: com.epwujiajun.DreamEcho
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    TARGETED_DEVICE_FAMILY: "1,2"  # iPhone 和 iPad
    SUPPORTS_MACCATALYST: false
    ENABLE_PREVIEWS: true
    DEVELOPMENT_TEAM: DRM95Z373U

# 为避免解析错误，明确提供空依赖数组或省略

targets:
  DreamEcho:
    type: application
    platform: iOS
    sources:
      - path: DreamEchoApp/Sources
        name: Sources
        type: group
    resources:
      - path: DreamEchoApp/Assets.xcassets
      - path: DreamEchoApp/Resources
    info:
      path: DreamEchoApp/Resources/Info.plist
      properties:
        CFBundleName: $(PRODUCT_NAME)
        CFBundleDisplayName: 梦境回声
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        API_BASE_URL: "https://api.dreamecho.ai"
        API_EVENTS_URL: "https://api.dreamecho.ai"
        ENABLE_HAPTICS: "true"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        INFOPLIST_FILE: DreamEchoApp/Resources/Info.plist
        DEVELOPMENT_ASSET_PATHS: '"DreamEchoApp/Preview Content"'
        ENABLE_PREVIEWS: true
    dependencies: []

  DreamEchoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DreamEchoApp/Tests
        name: Tests
        type: group
    dependencies:
      - target: DreamEcho

schemes:
  DreamEcho:
    build:
      targets:
        DreamEcho: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: DreamEchoTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

