"""add is_public column to dream and initialize tables

Revision ID: a50431c0e9f7
Revises: 9a38ac172975
Create Date: 2025-11-01 16:07:33.106571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50431c0e9f7'
down_revision = '9a38ac172975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('blockchain', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trading_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('royalty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('preview_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nft_tx_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('interpretation_file')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=200), nullable=True))

    with op.batch_alter_table('dream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interpretation_file', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_public')
        batch_op.drop_column('status')
        batch_op.drop_column('nft_tx_hash')
        batch_op.drop_column('preview_image')
        batch_op.drop_column('royalty')
        batch_op.drop_column('trading_type')
        batch_op.drop_column('price')
        batch_op.drop_column('blockchain')
        batch_op.drop_column('tags')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
